dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install: 
  - pip install --ignore-installed --upgrade setuptools coveralls pytest-cov
  - pip install -e .

script:
  - pytest --cov=swn_database/

after_success:
  - coveralls